/*
* ============================================================================
*  Name     : CHideMusicApp from HideMusicApp.cpp
*  Part of  : HideMusic
*  Created  : 04/04/2005 by Sergio Padrino Recio
*  Implementation notes:
*
*     Initial content was generated by Series 60 AppWizard.
*  Version  :
*  Copyright: No hay xD
* ============================================================================
*/

// INCLUDE FILES
#include    "HideMusicApp.h"
#include    "HideMusicDocument.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CHideMusicApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CHideMusicApp::AppDllUid() const
    {
    return KUidHideMusic;
    }


// ---------------------------------------------------------
// CHideMusicApp::CreateDocumentL()
// Creates CHideMusicDocument object
// ---------------------------------------------------------
//
CApaDocument* CHideMusicApp::CreateDocumentL()
    {
    return CHideMusicDocument::NewL( *this );
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication()
// Constructs CHideMusicApp
// Returns: created application object
// ---------------------------------------------------------
//
EXPORT_C CApaApplication* NewApplication()
    {
    return new CHideMusicApp;
    }

// ---------------------------------------------------------
// E32Dll(TDllReason)
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
GLDEF_C TInt E32Dll( TDllReason )
    {
    return KErrNone;
    }

// End of File

